language: node_js
node_js:
- lts/*
before_install:
- npm install -g @angular/cli
install:
- npm install
- cd server
- npm install
- cd ..
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: Yggzx/smOgkbZTgAfGbMCDgOvweecC9Ij8GBmaHVWJsPN1xKX9fkP9DYvTYu6U4ISqSvIPlRSGfljTrF7a4xY9RUq0jc3ECdc/JyPPzrueTvTsfQHvuRhb86RgU/XJNQhhUsmQzvEImvLDLdd2dyUta+LHebbL1RMi/XRvWQBLWuhT7HNRwAp+BaxLf4Kqy7c3kKS1UUcbxbAXroVJlbMTjaiXjC2vMxJrpla+2NxSYYonz5zR6mJojYRoJULjVVjr2JyVitVXT2FowOAhQZFj7EfJzadRCY8gh6llhoB28x/5KZu6QEORdur98s/n72QpQCxt9M9RkJLgMsi19DVwbiCQQmggndq7bisEskTc00yPFiMbS6ANOaahu+ybcOkPW7rqTPFaD9YOiXaAmEZpRUIXdyC87LXpxIH5fqRRDIQFhxYjVh+kqTJ5IcoVZGEU3Jbi0/VqcxMHuaW732GS7jlQwi+P2QlF77l+B95OBL5D+6N/vC7nTbP91/IrUFrVT4ybUc5xfVxXVRXXaAHeJg/JLsW6+tRAJohe/wvVJZdu/U550wlVl4kFfAxGtBInPI4XCOi8PXE3N8Euc3lwxZMvXZXO2gtBrwWiDumFCHyUVMP3hwiKN/gjBTjzlZrtS61yJxg4p0Gk3N8TDQenAFcrDxSHSAD7SiWEDd7rs=
  app: angular-final-project
  on:
    repo: yehor-akunishnikov/angular-final
  skip_cleanup: 'true'
